In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import pickle
from tqdm import tqdm

In [4]:
with open('data.pkl', 'rb') as f:
    data = pickle.load(f)

print(type(data))
print(data.shape)
print(data[:2, :])

<class 'numpy.ndarray'>
(506, 6)
[[-1.2879095  -0.12001342 -1.45900038 -0.66660821 -0.14421743  1.85884913]
 [-0.59338101  0.36716642 -0.30309415 -0.98732948 -0.74026221  1.81901037]]


In [5]:
X = data[:, :5]
print(type(X))
print(X.shape)
print(X[:5])

<class 'numpy.ndarray'>
(506, 5)
[[-1.2879095  -0.12001342 -1.45900038 -0.66660821 -0.14421743]
 [-0.59338101  0.36716642 -0.30309415 -0.98732948 -0.74026221]
 [-0.59338101 -0.26581176 -0.30309415 -0.98732948 -0.74026221]
 [-1.30687771 -0.80988851  0.1130321  -1.10611514 -0.83528384]
 [-1.30687771 -0.51117971  0.1130321  -1.10611514 -0.83528384]]


In [6]:
Y = data[:, -1]
print(type(Y))
print(Y.shape)
print(Y[:5])

<class 'numpy.ndarray'>
(506,)
[1.85884913 1.81901037 1.81989281 1.68590132 1.68590132]


In [7]:
w = np.random.normal(loc = 0.0 ,scale = 1.0, size = (9, ))
w

array([-0.1943402 , -0.09984745,  0.21234262, -1.00732188,  3.50506384,
        1.1019923 , -0.74740101,  0.54110347,  0.46447393])

In [8]:
def compute_sigmoid(z):
    
    denominator = np.add(1, np.exp(-z))
    
    sig = np.divide(1, denominator)
    
    return sig

In [9]:
def compute_loss(y, y_hat):
    
    diff = np.subtract(y, y_hat)
    
    diff_square = np.square(diff)
    
    loss = np.divide(diff_square, -2)
    
    return loss

In [ ]:
def copmute_del_z7__by__del_w5(z6, f5):

    return np.multiply(z6, f5)

In [ ]:
def copmute_del_loss__by__del_w5():
    
    ## Yet to develop
    return True

In [ ]:
def copmute_del_z7__by__del_w4(z6, f4):

    return np.multiply(z6, f4)

In [ ]:
def copmute_del_loss__by__del_w4():
    
    ## Yet to develop
    return True

In [ ]:
def copmute_del_z5__by__del_w3(f3):

    return f3

In [ ]:
def copmute_del_z6__by__del_z5(z5):

    return np.cos(z5)

In [ ]:
def copmute_del_z7__by__del_z6(f4, f5, w4, w5):

    return np.add(np.multiply(f4, w4), np.multiply(f5, , w5))

In [ ]:
def copmute_del_z8__by__del_z7():
        
    return 1

In [ ]:
def copmute_del_z9__by__del_z8(z8):
        
    return compute_sigmoid(z8) * [1 - compute_sigmoid(z8)]

In [ ]:
def copmute_del_z10__by__del_z9():
    
    return 1

In [ ]:
def copmute_del_y_hat__by__del_z10():
    
    return 1

In [ ]:
def copmute_del_loss__by__del_w3():
    
    ## Yet to develop
    return True

In [ ]:
def copmute_del_z1__by__del_w2(f1, f2, w1, w2):
    
    linear_eqn = np.add(np.multiply(f1, w1), np.multiply(f2, w2))
    
    grad = np.multiply(2 * f2, linear_eqn)
    
    return grad

In [ ]:
def copmute_del_loss__by__del_w2():
    
    return True

In [ ]:
def copmute_del_z1__by__del_w1(f1, f2, w1, w2):
    
    linear_eqn = np.add(np.multiply(f1, w1), np.multiply(f2, w2))
    
    grad = np.multiply(2 * f1, linear_eqn)
    
    return grad

In [ ]:
def copmute_del_z2__by__del_z1(z_01_mul_z_02, w6):
    
    return np.exp(np.add(z_01_mul_z_02, w6))

In [ ]:
def copmute_del_z3__by__del_z2():
    
    return 1

In [14]:
def copmute_del_z4__by__del_z3(z3):
    
    tanh_square = np.square(tanh(z3))
    
    return np.subtract(1, tanh_square)

In [ ]:
def copmute_del_y_hat__by__del_z4():
    
    return 1

In [13]:
def copmute_del_loss__by__del_y_hat(y, y_hat):
    
    return -np.subtract(y, y_hat)

In [12]:
def copmute_del_loss__by__del_w0():
    
    return True

In [10]:
epochs = 1
for epoch in range(epochs):
    
    for (f1, f2, f3, f4, f5), y in zip(X, Y):
        

        """
           FORWARD PROPAGATION
           -------------------
           
        Here we're calculating following node values
        
        z_01, z_02, z_01_mul_z_02
        AND
        z1, z2, z3, z4, z5
        """
        z_01 = np.multiply(f1, w[0])
        z_02 = np.multiply(f2, w[1])
        
        z_01_mul_z_02 = np.multiply(z_01, z_02)
        
        z_01_mul_z_02_square = np.square(z_01_mul_z_02)
        
        z1 = np.add(z_01_mul_z_02_square, w[5])
        
        z2 = np.exp(z1)
        
        z3 = np.add(z2, w[6])
        
        z4 = np.tanh(z3)


        """
        Here we're calculating following node values
        
        z_03, z6
        """
        z_03 = np.multiply(f3, w[2])
        
        z6 = np.sin(z_03)
        

        """
        Here we're calculating following node values
        
        z_04, z_05, z_04_mul_z_05
        AND
        z7, z8, z9, z10
        """
        z_04 = np.multiply(f3, w[3])
        
        z_05 = np.multiply(f3, w[4])
        
        z_04_mul_z_05 = np.multiply(z_04, z_05)
        
        z7 = np.add(z6, z_04_mul_z_05)
        
        z8 = np.add(z7, w[7])
        
        z9 = compute_sigmoid(z8)
        
        z10 = np.add(z9, w[8])
        
        
        """
        Here we're calculating following node values

        y_hat, loss
        """
        y_hat = np.add(z5, z10)
        
        loss = compute_loss(y, y_hat)
        
        
        break