In [172]:
import numpy as np
import pandas as pd

In [173]:
import matplotlib.pyplot as plt
%matplotlib inline

In [174]:
import pickle
from tqdm import tqdm

In [175]:
with open('data.pkl', 'rb') as f:
    data = pickle.load(f)

print(type(data))
print(data.shape)
print(data[:2, :])

<class 'numpy.ndarray'>
(506, 6)
[[-1.2879095  -0.12001342 -1.45900038 -0.66660821 -0.14421743  1.85884913]
 [-0.59338101  0.36716642 -0.30309415 -0.98732948 -0.74026221  1.81901037]]


In [176]:
X = data[:, :5]
print(type(X))
print(X.shape)
print(X[:5])

<class 'numpy.ndarray'>
(506, 5)
[[-1.2879095  -0.12001342 -1.45900038 -0.66660821 -0.14421743]
 [-0.59338101  0.36716642 -0.30309415 -0.98732948 -0.74026221]
 [-0.59338101 -0.26581176 -0.30309415 -0.98732948 -0.74026221]
 [-1.30687771 -0.80988851  0.1130321  -1.10611514 -0.83528384]
 [-1.30687771 -0.51117971  0.1130321  -1.10611514 -0.83528384]]


In [177]:
Y = data[:, -1]
print(type(Y))
print(Y.shape)
print(Y[:5])

<class 'numpy.ndarray'>
(506,)
[1.85884913 1.81901037 1.81989281 1.68590132 1.68590132]


In [178]:
#w = np.random.normal(loc = 0.0 ,scale = 1.0, size = (9, ))
"""

w = [-0.85278606, -0.0906873 ,  0.33943315,  1.08441533, -2.20272759,
       -0.07922769, -1.06343281,  0.25353341,  0.26889213]
w       
"""

w=np.ones(9)*0.1

In [179]:
def sigmoid(z):
    
    denominator = np.add(1, np.exp(-z))
    
    sig = np.divide(1, denominator)
    
    return sig

In [180]:
def compute_loss(y, y_hat):
    
    diff = np.subtract(y, y_hat)
    
    diff_square = np.square(diff)
    
    loss = np.divide(diff_square, -2)
    
    return loss

In [181]:
def copmute_del_z10__by__del_w9(z9):
    
    return z9

In [182]:
def copmute_del_loss__by__del_w9(z9, y, y_hat):
    """
    """
    del_loss__by__del_w9 = np.prod([
        
        copmute_del_loss__by__del_y_hat(y, y_hat),
        copmute_del_y_hat__by__del_z10(),
        copmute_del_z10__by__del_w9(z9)
                        ])
    
    return del_loss__by__del_w9

In [183]:
def copmute_del_z8__by__del_w8():
    
    return 1

In [184]:
def copmute_del_loss__by__del_w8(z8, y, y_hat):
    """
    """
    del_loss__by__del_w8 = np.prod([
        
        copmute_del_loss__by__del_y_hat(y, y_hat),
        copmute_del_y_hat__by__del_z10(),
        copmute_del_z10__by__del_z9(),
        copmute_del_z9__by__del_z8(z8),
        copmute_del_z8__by__del_w8(),
                        ])
    
    return del_loss__by__del_w8

In [185]:
def copmute_del_z3__by__del_w7(z2):
    
    return z2

In [186]:
def copmute_del_loss__by__del_w7(z2, z3, y, y_hat):
    """
    """

    del_loss__by__del_w7 = np.prod([
                            copmute_del_loss__by__del_y_hat(y, y_hat),
                            copmute_del_y_hat__by__del_z4(),
                            copmute_del_z4__by__del_z3(z3),
                            copmute_del_z3__by__del_w7(z2)
                        ])
    
    return del_loss__by__del_w7

In [187]:
def copmute_del_z1__by__del_w6():
    
     return 1

In [188]:
def copmute_del_loss__by__del_w6(z3, z_01_mul_z_02_square, y, y_hat, w):
    """
    """
    w1, w2, w3, w4, w5, w6, w7, w8, w9 = w
    
    del_loss__by__del_w6 = np.prod([
        
                            copmute_del_loss__by__del_y_hat(y, y_hat),
                            copmute_del_y_hat__by__del_z4(),
        
                            copmute_del_z4__by__del_z3(z3),
                            copmute_del_z3__by__del_z2(),
                            copmute_del_z2__by__del_z1(z_01_mul_z_02_square, w6),
                            copmute_del_z1__by__del_w6()
                        ])
    
    return del_loss__by__del_w6

In [189]:
def copmute_del_z7__by__del_w5(z6, f5):

    return np.multiply(z6, f5)

In [190]:
def copmute_del_loss__by__del_w5(f5, z6, z8, y, y_hat):
    
    w1, w2, w3, w4, w5, w6, w7, w8, w9 = w
    
    del_loss__by__del_w5 = np.prod([
        copmute_del_loss__by__del_y_hat(y, y_hat),
        copmute_del_y_hat__by__del_z10(),
        copmute_del_z10__by__del_z9(),
        copmute_del_z9__by__del_z8(z8),
        copmute_del_z8__by__del_z7(),
        copmute_del_z7__by__del_w5(z6, f5)
    ])
    
    return del_loss__by__del_w5

In [191]:
def copmute_del_z7__by__del_w4(z6, f4):

    return np.multiply(z6, f4)

In [192]:
def copmute_del_loss__by__del_w4(f4, z6, z8, y, y_hat):
    
    w1, w2, w3, w4, w5, w6, w7, w8, w9 = w
    
    del_loss__by__del_w4 = np.prod([
        
        copmute_del_loss__by__del_y_hat(y, y_hat),
        copmute_del_y_hat__by__del_z10(),
        copmute_del_z10__by__del_z9(),
        copmute_del_z9__by__del_z8(z8),
        copmute_del_z8__by__del_z7(),
        copmute_del_z7__by__del_w4(z6, f4)
    ])
    
    return del_loss__by__del_w4

In [193]:
def copmute_del_z5__by__del_w3(f3):

    return f3

In [194]:
def copmute_del_z6__by__del_z5(z5):

    return np.cos(z5)

In [195]:
def copmute_del_z7__by__del_z6(f4, f5, w4, w5):

    return np.add(np.multiply(f4, w4), np.multiply(f5, w5))

In [196]:
def copmute_del_z8__by__del_z7():
        
    return 1

In [197]:
def copmute_del_z9__by__del_z8(z8):
    
    a = sigmoid(z8)
    b = np.subtract(1, a)

    return np.multiply(a, b)

In [198]:
def copmute_del_z10__by__del_z9():
    
    return 1

In [199]:
def copmute_del_y_hat__by__del_z10():
    
    return 1

In [200]:
def copmute_del_loss__by__del_w3(f3, f4, f5, z5, z8, y, y_hat, w):
    
    w1, w2, w3, w4, w5, w6, w7, w8, w9 = w
    
    del_loss__by__del_w3 = np.prod([
        copmute_del_loss__by__del_y_hat(y, y_hat),
        copmute_del_y_hat__by__del_z10(),
        copmute_del_z10__by__del_z9(),
        copmute_del_z9__by__del_z8(z8),
        copmute_del_z8__by__del_z7(),
        copmute_del_z7__by__del_z6(f4, f5, w4, w5),
        copmute_del_z6__by__del_z5(z5),
        copmute_del_z5__by__del_w3(f3)        
    ])
    
    return del_loss__by__del_w3

In [201]:
def copmute_del_z1__by__del_w2(f1, f2, w1, w2):
    
    linear_eqn = np.add(np.multiply(f1, w1), np.multiply(f2, w2))
    
    grad = np.multiply(2 * f2, linear_eqn)
    
    return grad

In [202]:
def copmute_del_loss__by__del_w2(f1, f2, z_01_mul_z_02_square, w, y, y_hat):
    
    """
    """
    w1, w2, w3, w4, w5, w6, w7, w8, w9 = w
    
    del_loss__by__del_w1 = np.prod([
                            copmute_del_loss__by__del_y_hat(y, y_hat),
                            copmute_del_y_hat__by__del_z4(),
                            copmute_del_z4__by__del_z3(z3),
                            copmute_del_z3__by__del_z2(),
                            copmute_del_z2__by__del_z1(z_01_mul_z_02_square, w6),
                            copmute_del_z1__by__del_w2(f1, f2, w1, w2),
                        ])
    
    return del_loss__by__del_w1

In [203]:
def copmute_del_z1__by__del_w1(f1, f2, w1, w2):
    
    linear_eqn = np.add(np.multiply(f1, w1), np.multiply(f2, w2))
    
    grad = np.multiply(2 * f1, linear_eqn)
    
    return grad

In [204]:
def copmute_del_z2__by__del_z1(z_01_mul_z_02_square, w6):
    
    return np.exp(np.add(z_01_mul_z_02_square, w6))

In [205]:
def copmute_del_z3__by__del_z2():
    
    return 1

In [206]:
def copmute_del_z4__by__del_z3(z3):
    
    tanh_square = np.square(np.tanh(z3))
    
    return np.subtract(1, tanh_square)

In [207]:
def copmute_del_y_hat__by__del_z4():
    
    return 1

In [208]:
def copmute_del_loss__by__del_y_hat(y, y_hat):
    
    return -np.subtract(y, y_hat)

In [209]:
def copmute_del_loss__by__del_w1(f1, f2, z_01_mul_z_02_square, w, y, y_hat):
    """
    """
    w1, w2, w3, w4, w5, w6, w7, w8, w9 = w
    
    del_loss__by__del_w1 = np.prod([
                            copmute_del_loss__by__del_y_hat(y, y_hat),
                            copmute_del_y_hat__by__del_z4(),
                            copmute_del_z4__by__del_z3(z3),
                            copmute_del_z3__by__del_z2(),
                            copmute_del_z2__by__del_z1(z_01_mul_z_02_square, w6),
                            copmute_del_z1__by__del_w1(f1, f2, w1, w2),
                        ])
    
    return del_loss__by__del_w1

In [215]:
epochs = 100
lr = 0.0001
loss_trace = list()

for epoch in tqdm(range(epochs)):
    
    loss_temp = 0.0
    for (f1, f2, f3, f4, f5), y in zip(X, Y):
        print(f1, f2, f3, f4, f5)

        """
           FORWARD PROPAGATION
           -------------------
           
        Here we're calculating following node values
        
        z_01, z_02, z_01_mul_z_02
        AND
        z1, z2, z3, z4, z5
        """
        z_01 = np.multiply(f1, w[0])
        z_02 = np.multiply(f2, w[1])
        
        z_01_add_z_02 = np.add(z_01, z_02)
        
        z_01_add_z_02_square = np.square(z_01_add_z_02)
        
        z1 = np.add(z_01_add_z_02_square, w[5])
        
        z2 = np.exp(z1)
        
        z3 = np.add(z2, w[6])
        
        z4 = np.tanh(z3)


        """
        Here we're calculating following node values
        
        z_03, z6
        """
        z5 = np.multiply(f3, w[2])
        
        z6 = np.sin(z5)
        

        """
        Here we're calculating following node values
        
        z_04, z_05, z_04_mul_z_05
        AND
        z7, z8, z9, z10
        """
        z_04 = np.multiply(f4, w[3])
        
        z_05 = np.multiply(f5, w[4])
        
        z_04_add_z_05 = np.add(z_04, z_05)

        z7 = np.multiply(z6, z_04_add_z_05) 
        
        z8 = np.add(z7, w[7])
        
        #z9
        sig = sigmoid(z8)
        
        z10 = np.multiply(sig, w[8])
        
        
        """
        Here we're calculating following node values

        y_hat, loss
        """
        y_hat = np.add(z4, z10)
        
        loss = compute_loss(y, y_hat)
        
        loss_temp += loss
        
        """
        del_loss__by__del_w1 = copmute_del_loss__by__del_w1(f1, f2, z_01_mul_z_02_square, w, y, y_hat)
        
        del_loss__by__del_w2 = copmute_del_loss__by__del_w2(f1, f2, z_01_mul_z_02_square, w, y, y_hat)
        
        del_loss__by__del_w3 = copmute_del_loss__by__del_w2(f1, f2, z_01_mul_z_02_square, w, y, y_hat)
        
        del_loss__by__del_w4 = copmute_del_loss__by__del_w4(f4, z6, z8, y, y_hat)
        
        del_loss__by__del_w5 = copmute_del_loss__by__del_w5(f5, z6, z8, y, y_hat)
        
        del_loss__by__del_w6 = copmute_del_loss__by__del_w6(z3, z_01_mul_z_02_square, y, y_hat, w)
        
        del_loss__by__del_w7 = copmute_del_loss__by__del_w7(z2, z3, y, y_hat)
        
        del_loss__by__del_w8 = copmute_del_loss__by__del_w8(z8, y, y_hat)
        
        del_loss__by__del_w9 = copmute_del_loss__by__del_w9(z9, y, y_hat)
        
        """
        l_w1 = copmute_del_loss__by__del_w1(f1, f2, z_01_mul_z_02_square, w, y, y_hat)
        
        l_w2 = copmute_del_loss__by__del_w2(f1, f2, z_01_mul_z_02_square, w, y, y_hat)
        
        l_w3 = copmute_del_loss__by__del_w2(f1, f2, z_01_mul_z_02_square, w, y, y_hat)
        
        l_w4 = copmute_del_loss__by__del_w4(f4, z6, z8, y, y_hat)
        
        l_w5 = copmute_del_loss__by__del_w5(f5, z6, z8, y, y_hat)
        
        l_w6 = copmute_del_loss__by__del_w6(z3, z_01_mul_z_02_square, y, y_hat, w)
        
        l_w7 = copmute_del_loss__by__del_w7(z2, z3, y, y_hat)
        
        l_w8 = copmute_del_loss__by__del_w8(z8, y, y_hat)
        
        l_w9 = copmute_del_loss__by__del_w9(z9, y, y_hat)

        w = [ np.subtract(weight, -lr * l_w) for weight, l_w in zip(w, [l_w1, l_w2, l_w3, l_w4, l_w5, l_w6, l_w7, l_w8, l_w9])]
        break
    avg_loss = np.divide(loss_temp, X.shape[0])
    loss_trace.append(avg_loss)
    break

  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

-1.287909498957745 -0.12001341619804987 -1.4590003802772022 -0.6666082090210984 -0.14421743255530314


In [211]:
print(w)

[0.0999938535826559, 0.09999942724815414, 0.09999942724815414, 0.09999880558023803, 0.09999974159311402, 0.09998305163430636, 0.09998305163430636, 0.09998767540082415, 0.09997887837088057]


In [212]:
loss_trace

[-0.00025413062048935817]